source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/mafeng-Bryant/Specs.git'
use_frameworks!

target 'MFileManager_Example' do
  pod 'MFileManager', :path => '../'

  target 'MFileManager_Tests' do
    inherit! :search_paths

    
  end
end
